# Generated by Django 4.2.4 on 2023-08-28 17:54

import djmoney.models.fields
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0040_transaction_transaction_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name="leg",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=4,
                max_digits=16,
                default_currency="CLP",
                help_text="Record debits as positive, credits as negative",
            ),
        ),
    ]
