# Generated by Django 4.2.4 on 2023-08-28 17:54

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0041_fix_leg_amunt_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name="statementline",
            name="amount",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=16,
                verbose_name="amount",
            ),
        ),
    ]
